### ISSUE TITLE
Remove unused file publish npm

### ISSUE THREAD

**Issue by hong4rc** [binhqd/str_shorten#36]
I see many unused file in `str_shorten`:
 - coverage
 - docs
 - test script, etc..

We just need `index.js` file(1KB) but `str_shorten` is big(>5.4MB).

**Comment by binhqd** [comment]
Thanks @Hongarc for your feedback.

This repository actually is in used for 2 purposes:
1. Development: We need coverage, docs and test script to make sure all work well with community standard, so other can clone and continue develop with their own need
2. For use: With people that just want to use it. They just need to install with `yarn` and `npm` and the source will be in `node_modules` folder. If the `index.js` is used then only this file will be included in the source code and there won't cost any extra size for their project
